services:
  eventstore:
    image: kurrentplatform/kurrentdb:25.0.0-x64-8.0-bookworm-slim
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
    environment:
      #######################
      # Application Options 
      #######################
      KURRENTDB_ALLOW_ANONYMOUS_ENDPOINT_ACCESS: false
      KURRENTDB_ALLOW_ANONYMOUS_STREAM_ACCESS: false 
      KURRENTDB_ALLOW_UNKNOWN_OPTIONS: false
      KURRENTDB_CONFIG: /etc/kurrentdb/kurrentdb.conf
      KURRENTDB_DISABLE_HTTP_CACHING: false
      KURRENTDB_ENABLE_HISTOGRAMS: false
      KURRENTDB_HELP: false
      KURRENTDB_INSECURE: false
      KURRENTDB_LOG_FAILED_AUTHENTICATION_ATTEMPTS: false 
      KURRENTDB_LOG_HTTP_REQUESTS: false 
      KURRENTDB_MAX_APPEND_EVENT_SIZE: 2147483647
      KURRENTDB_MAX_APPEND_SIZE: 1048576
      KURRENTDB_OVERRIDE_ANONYMOUS_ENDPOINT_ACCESS_FOR_GOSSIP: true
      KURRENTDB_SKIP_INDEX_SCAN_ON_READS: FALSE
      KURRENTDB_STATS_PERIOD_SEC: 30
      KURRENTDB_TELEMETRY_OPTOUT: false
      KURRENTDB_VERSION: false
      KURRENTDB_WHAT_IF: false
      KURRENTDB_WORKER_THREADS: 5

      #######################
      # AuthN/AuthZ Options
      #######################
      # KURRENTDB_AUTHENTICATION_CONFIG: 
      KURRENTDB_AUTHENTICATION_TYPE: internal 
      # KURRENTDB_AUTHORIZATION_CONFIG:
      KURRENTDB_AUTHORIZATION_TYPE: internal 
      KURRENTDB_DISABLE_FIRST_LEVEL_HTTP_AUTHORIZATION: false

      #######################
      # Certificate Options
      #######################
      KURRENTDB_CERTIFICATE_FILE: /etc/kurrentdb/certs/node.crt
      KURRENTDB_CERTIFICATE_PRIVATE_KEY_FILE: /etc/kurrentdb/certs/node.key
      # KURRENTDB_CERTIFICATE_RESERVED_NODE_COMMON_NAME: 
      KURRENTDB_TRUSTED_ROOT_CERTIFICATES_PATH: /etc/kurrentdb/ca
      # KURRENTDB_CERTIFICATE_PASSWORD:
      # KURRENTDB_PRIVATE_KEY_PASSWORD:
      # KURRENTDB_CERTIFICATE_STORE_LOCATION:
      # KURRENTDB_CERTIFICATE_STORE_NAME:
      # KURRENTDB_CERTIFICATE_SUBJECT_NAME:
      # KURRENTDB_CERTIFICATE_THUMBPRINT:
      # KURRENTDB_TRUSTED_ROOT_CERTIFICATE_STORE_LOCATION:
      # KURRENTDB_TRUSTED_ROOT_CERTIFICATE_STORE_NAME:
      # KURRENTDB_TRUSTED_ROOT_CERTIFICATE_SUBJECT_NAME:
      # KURRENTDB_TRUSTED_ROOT_CERTIFICATE_THUMBPRINT:

      ###################
      # Cluster Options
      ###################
      KURRENTDB_ARCHIVER: false
      KURRENTDB_CLUSTER_DNS: fake.dns
      KURRENTDB_CLUSTER_GOSSIP_PORT: 2113
      KURRENTDB_CLUSTER_SIZE: 1
      KURRENTDB_DEAD_MEMBER_REMOVAL_PERIOD_SEC: 1800
      KURRENTDB_DISCOVER_VIA_DNS: false
      KURRENTDB_GOSSIP_ALLOWED_DIFFERENCE_MS: 60000
      KURRENTDB_GOSSIP_INTERVAL_MS: 2000
      # KURRENTDB_GOSSIP_SEED:
      KURRENTDB_GOSSIP_TIMEOUT_MS: 2500
      KURRENTDB_LEADER_ELECTION_TIMEOUT_MS: 1000
      KURRENTDB_NODE_PRIORITY: 0
      KURRENTDB_QUORUM_SIZE: 1
      KURRENTDB_READ_ONLY_REPLICA: false
      KURRENTDB_STREAM_INFO_CACHE_CAPACITY: 0
      KURRENTDB_UNSAFE_ALLOW_SURPLUS_NODES: false

      ####################
      # Database Options
      ####################
      KURRENTDB_CACHED_CHUNKS: -1
      KURRENTDB_CHUNK_INITIAL_READER_COUNT: 5
      KURRENTDB_CHUNK_SIZE: 268435456
      KURRENTDB_CHUNKS_CACHE_SIZE: 536871424
      KURRENTDB_COMMIT_TIMEOUT_MS: 2000
      KURRENTDB_DB: /var/lib/kurrentdb
      KURRENTDB_DB_LOG_FORMAT: V2
      KURRENTDB_DISABLE_SCAVENGE_MERGING: false
      KURRENTDB_HASH_COLLISION_READ_LIMIT: 100
      # KURRENTDB_INDEX:
      KURRENTDB_INDEX_CACHE_DEPTH: 16
      KURRENTDB_INDEX_CACHE_SIZE: 0
      KURRENTDB_INITIALIZATION_THREADS: 1
      KURRENTDB_MAX_AUTO_MERGE_INDEX_LEVEL: 2147483647
      KURRENTDB_MAX_MEM_TABLE_SIZE: 1000000
      KURRENTDB_MAX_TRUNCATION: 268435456
      KURRENTDB_MEM_DB: false
      KURRENTDB_MIN_FLUSH_DELAY_MS: 2
      KURRENTDB_PREPARE_TIMEOUT_MS: 2000
      KURRENTDB_READER_THREADS_COUNT: 4
      KURRENTDB_REDUCE_FILE_CACHE_PRESSURE: false
      KURRENTDB_SCAVENGE_BACKEND_CACHE_SIZE: 67108864
      KURRENTDB_SCAVENGE_BACKEND_PAGE_SIZE: 16384
      KURRENTDB_SCAVENGE_HASH_USERS_CACHE_CAPACITY: 100000
      KURRENTDB_SCAVENGE_HISTORY_MAX_AGE: 30
      KURRENTDB_SKIP_DB_VERIFY: false
      KURRENTDB_SKIP_INDEX_VERIFY: false 
      KURRENTDB_STATS_STORAGE: File 
      KURRENTDB_STREAM_EXISTENCE_FILTER_SIZE: 256000000
      KURRENTDB_TRANSFORM: identity
      KURRENTDB_UNBUFFERED: false      
      KURRENTDB_UNSAFE_DISABLE_FLUSH_TO_DISK: false
      KURRENTDB_UNSAFE_IGNORE_HARD_DELETE: false
      KURRENTDB_USE_INDEX_BLOOM_FILTERS: true 
      KURRENTDB_WRITE_STATS_TO_DB: false
      KURRENTDB_WRITE_THROUGH: false
      KURRENTDB_WRITE_TIMEOUT_MS: 2000
      
      ########################
      # Default User Options
      ########################
      # KURRENTDB_DEFAULT_ADMIN_PASSWORD (secret)
      # KURRENTDB_DEFAULT_OPS_PASSWORD (secret)

      ############################
      # Development Mode Options
      ############################
      KURRENTDB_DEV: false 
      KURRENTDB_REMOVE_DEV_CERTS: false

      ################
      # gRPC Options
      ################
      KURRENTDB_KEEP_ALIVE_INTERVAL: 1000
      KURRENTDB_KEEP_ALIVE_TIMEOUT: 1000

      #####################
      # Interface Options
      #####################
      KURRENTDB_ADVERTISE_HOST_TO_CLIENT_AS: 127.0.0.1
      KURRENTDB_ADVERTISE_NODE_PORT_TO_CLIENT_AS: 2113
      KURRENTDB_CONNECTION_PENDING_SEND_BYTES_THRESHOLD: 10485760
      KURRENTDB_CONNECTION_QUEUE_SIZE_THRESHOLD: 50000
      KURRENTDB_DISABLE_ADMIN_UI: false
      KURRENTDB_DISABLE_GOSSIP_ON_HTTP: false
      KURRENTDB_DISABLE_STATS_ON_HTTP: false 
      KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP: true
      KURRENTDB_ENABLE_TRUSTED_AUTH: false 
      KURRENTDB_ENABLE_UNIX_SOCKET: false 
      # KURRENTDB_NODE_HOST_ADVERTISE_AS: 
      KURRENTDB_NODE_IP: 0.0.0.0
      KURRENTDB_NODE_PORT: 2113
      KURRENTDB_NODE_PORT_ADVERTISE_AS: 0
      KURRENTDB_REPLICATION_HEARTBEAT_INTERVAL: 700
      KURRENTDB_REPLICATION_HEARTBEAT_TIMEOUT: 700
      # KURRENTDB_REPLICATION_HOST_ADVERTISE_AS:
      KURRENTDB_REPLICATION_IP: 0.0.0.0
      KURRENTDB_REPLICATION_PORT: 1112
      KURRENTDB_REPLICATION_TCP_PORT_ADVERTISE_AS: 0

      ###################
      # Logging Options
      ###################
      KURRENTDB_DISABLE_LOG_FILE: false
      KURRENTDB_LOG: /var/log/kurrentdb
      KURRENTDB_LOG_CONFIG: logconfig.json 
      KURRENTDB_LOG_CONSOLE_FORMAT: Plain 
      KURRENTDB_LOG_FILE_INTERVAL: Day
      KURRENTDB_LOG_FILE_RETENTION_COUNT: 31
      KURRENTDB_LOG_FILE_SIZE: 1073741824
      KURRENTDB_LOG_LEVEL: Default

      ######################
      # Projection Options
      ######################
      KURRENTDB_FAULT_OUT_OF_ORDER_PROJECTIONS: false
      KURRENTDB_MAX_PROJECTION_STATE_SIZE: 2147483647
      KURRENTDB_PROJECTION_COMPILATION_TIMEOUT: 500
      KURRENTDB_PROJECTION_EXECUTION_TIMEOUT: 250
      KURRENTDB_PROJECTION_THREADS: 3
      KURRENTDB_PROJECTIONS_QUERY_EXPIRY: 5
      KURRENTDB_RUN_PROJECTIONS: All
      KURRENTDB_START_STANDARD_PROJECTIONS: true
      
    healthcheck:
      test: 
        [
          "CMD-SHELL",
          "curl --fail https://eventstore:2113/health/live || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 24
      start_period: 10s
    ports:
      - 2113:2113
    restart: always
    secrets:
      - kurrentdb_default_admin_password
      - kurrentdb_default_ops_password
    volumes:
      - "./.kurrent/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro"
      - "./.kurrent/root/ca:/etc/kurrentdb/ca:ro"
      - "./.kurrent/node1/cert:/etc/kurrentdb/certs:ro"
      - "./.kurrent/node1/data:/var/lib/kurrentdb"
      - "./.kurrent/node1/logs:/var/log/kurrentdb"

secrets:
  kurrentdb_default_admin_password:
    file: ./.kurrent/secrets/default_admin_password
    
  kurrentdb_default_ops_password:
    file: ./.kurrent/secrets/default_ops_password
    
